# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

reg_F <- function(R, Q, Q_r, Y, IND) {
    .Call(`_CppFunc_reg_F`, R, Q, Q_r, Y, IND)
}

reg_F2 <- function(R, Q, Q_r, Y) {
    .Call(`_CppFunc_reg_F2`, R, Q, Q_r, Y)
}

reg_F3 <- function(R, Q, Q_r, Y, K) {
    .Call(`_CppFunc_reg_F3`, R, Q, Q_r, Y, K)
}

reg_F4 <- function(R, Q, Q_r, Y, IND, K) {
    .Call(`_CppFunc_reg_F4`, R, Q, Q_r, Y, IND, K)
}

reg_cov <- function(R, Q, Y, IND, K) {
    .Call(`_CppFunc_reg_cov`, R, Q, Y, IND, K)
}

reg_F_ROI <- function(R, Q, Q_r, Y, K) {
    .Call(`_CppFunc_reg_F_ROI`, R, Q, Q_r, Y, K)
}

res_vox <- function(Q, Y, IND) {
    .Call(`_CppFunc_res_vox`, Q, Y, IND)
}

res_ROI <- function(Q, Y) {
    .Call(`_CppFunc_res_ROI`, Q, Y)
}

perm_mri <- function(Q, Q_r, Y, DF, K) {
    .Call(`_CppFunc_perm_mri`, Q, Q_r, Y, DF, K)
}

perm_mri_t <- function(Q, Q_r, R, Y, varX_div_DF) {
    .Call(`_CppFunc_perm_mri_t`, Q, Q_r, R, Y, varX_div_DF)
}

IV_F <- function(X, R, Q, Q_r, Y, IND, K) {
    .Call(`_CppFunc_IV_F`, X, R, Q, Q_r, Y, IND, K)
}

IV_F_ROI <- function(X, R, Q, Q_r, Y, K) {
    .Call(`_CppFunc_IV_F_ROI`, X, R, Q, Q_r, Y, K)
}

lm_cpp <- function(X, Y) {
    .Call(`_CppFunc_lm_cpp`, X, Y)
}

lm_cpp_het <- function(X, Y) {
    .Call(`_CppFunc_lm_cpp_het`, X, Y)
}

lm_cpp_cluster <- function(X, Y, C) {
    .Call(`_CppFunc_lm_cpp_cluster`, X, Y, C)
}

iv_cpp <- function(X, Z, Y) {
    .Call(`_CppFunc_iv_cpp`, X, Z, Y)
}

iv_cpp_het <- function(X, Z, Y) {
    .Call(`_CppFunc_iv_cpp_het`, X, Z, Y)
}

iv_cpp_cluster <- function(X, Z, Y, C) {
    .Call(`_CppFunc_iv_cpp_cluster`, X, Z, Y, C)
}

RIDGE_K <- function(X, Y, K) {
    .Call(`_CppFunc_RIDGE_K`, X, Y, K)
}

RIDGE_multi_K <- function(X, Y, K) {
    .Call(`_CppFunc_RIDGE_multi_K`, X, Y, K)
}

RIDGE_L <- function(X, Y, L) {
    .Call(`_CppFunc_RIDGE_L`, X, Y, L)
}

RIDGE_L_AIC <- function(X, Y, L) {
    .Call(`_CppFunc_RIDGE_L_AIC`, X, Y, L)
}

RIDGE_L_Kfolds <- function(XtX, XtY, L) {
    .Call(`_CppFunc_RIDGE_L_Kfolds`, XtX, XtY, L)
}

SVD_cpp <- function(X) {
    .Call(`_CppFunc_SVD_cpp`, X)
}

RIDGE_IV_K <- function(X_input, Z_input, Y_input, K) {
    .Call(`_CppFunc_RIDGE_IV_K`, X_input, Z_input, Y_input, K)
}

Stdz <- function(mat) {
    .Call(`_CppFunc_Stdz`, mat)
}

make_res <- function(X, Y) {
    .Call(`_CppFunc_make_res`, X, Y)
}

get_XXt <- function(X) {
    .Call(`_CppFunc_get_XXt`, X)
}

get_XtX <- function(X) {
    .Call(`_CppFunc_get_XtX`, X)
}

get_cholinv <- function(X) {
    .Call(`_CppFunc_get_cholinv`, X)
}

